<center>
    <h1>Recurrent Neural Networks(RNNs)</h1>
</center>

# Brief Recap

Recurrent Neural Networks (RNNs) are a type of artificial neural network designed for processing sequential data, where the output depends not just on the current input but also on previous inputs. This makes them particularly well-suited for tasks like time series forecasting, language modeling, speech recognition, and machine translation. <br>
They were introduced in the 1980s. The foundational work on RNNs is attributed to John Hopfield, who introduced the Hopfield Network in 1982, and David Rumelhart, along with Geoffrey Hinton and Ronald J. Williams, who formalized the concept of backpropagation through time (BPTT) in the mid-1980s.



## RNN Architecture Description


<img src='assets/rnn.png' width=500/>

1. **Input Layer:** The input to an RNN is typically a sequence of vectors, where each element of the sequence corresponds to one time step. For example, in a sequence of words (like a sentence), each word can be represented as a vector (often a word embedding).
2. **Hidden Layer:** The defining feature of an RNN is its hidden state, which acts as a memory of the network. This state is updated at each time step based on the current input and the previous hidden state.
3. **Output Layer:** At each time step, the RNN can produce an output, which might be a prediction(e.g., the next word in a sentence), a classification(e.g., positive or negative sentiment of a sentence) or a final output after the whole sequence has been processed(e.g., classifying a video).  
4. **Recurrent Loop:** Unlike traditional neural networks, which process inputs independently, RNNs have recurrent connections that loop information back into the network. This loop allows information to flow from one time step to the next.

## Advantages of RNNs
* **Sequential Data Processing:** They can process input data one element at a time while retaining information about previous inputs, making them ideal for tasks where the order of data matters.
* **Memory of previous inputs:** Retains past information through hidden states, capturing context and temporal dependencies.
* **Parameter Efficiency:** Uses shared weights across time steps, reducing the number of parameters.
* **Variable-Length Inputs:** Can handle sequences of different lengths without architectural changes.
* **Contextual Understanding:** Captures broader context in tasks like sentiment analysis and question answering.

# Implementing RNNs with TensorFlow

TensorFlow provides an easy way to implement LSTM layers using the `tf.keras.layers.SimpleRNN` class. Here's an overview of the key components:
* `units`: Number of neurons in an RNN layer
* `input_shape` (`timesteps`, `input_dim`): Defines shape of the input to the RNN.`timesteps` refers to the number of time steps in each input sequence, and `input_dim` refers to the number of features in each time step.
* `return_sequences`: Determines whether to return the output for each time step (`True`) or only the final time step's output (`False`).
* `activation`: Specifies the activation function for the output layer.

For more detailed information, refer to the TensorFlow documentation on [SimpleRNN](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SimpleRNN).

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Input

# Define model parameters
input_dim = 10  # Number of features in each time step
timesteps = 5   # Number of time steps in each sequence
num_classes = 3 # Number of output classes

# Build the RNN model
model = Sequential()

# Add an RNN layer
model.add(Input(shape=(timesteps, input_dim)))
model.add(SimpleRNN(50, return_sequences=False))

# Add a dense output layer
model.add(Dense(num_classes, activation='softmax'))

# Summarize the model
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 50)                  │           3,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 3)                   │             153 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,203 (12.51 KB)

 Trainable params: 3,203 (12.51 KB)

 Non-trainable params: 0 (0.00 B)

**SimpleRNN Layer:**

This is the recurrent layer with 50 units (neurons). It takes a sequence of shape (timesteps, input_dim) as input, where timesteps = 5 and input_dim = 10.
The parameter `return_sequences=False` means that only the output of the last time step is passed to the next layer.

**Dense Layer:**

A fully connected layer with num_classes = 3 neurons, each corresponding to one output class. The `activation` function is softmax, which is typically used for multi-class classification tasks.

# Sample Q/A Use Case with RNN

Let's build a **Question Answering problem** and solve it using `SimpleRNN`.

Preparing data for **Recurrent Neural Networks(RNNs)** in TensorFlow involves several key steps to ensure that your sequential data is in the right format for training and evaluation.



In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [3]:
# Dummy dataset
questions = [
    "What is your name?",
    "How are you?",
    "What is your profession?",
    "Where do you live?",
    "What is your favorite color?"
]

# Corresponding answers (encoded as class labels)
# We'll assign a unique class to each answer
answers = [0, 1, 0, 2, 3]

### Tokenizing and Preprocessing
* `Tokenizer`: It is used to convert words in questions into integer sequences.
* `pad_sequences`: It ensures that all sequences are of same length by padding shorter sequences with zeros.

In [4]:
# Initialize tokenizer to convert text to sequences

tokenizer = Tokenizer()
tokenizer.fit_on_texts(questions)

You can check how each word is encoded using `tokenizer.word_index`

In [6]:
tokenizer.word_index

{'what': 1,
 'is': 2,
 'your': 3,
 'you': 4,
 'name': 5,
 'how': 6,
 'are': 7,
 'profession': 8,
 'where': 9,
 'do': 10,
 'live': 11,
 'favorite': 12,
 'color': 13}

In [7]:
# Convert text to sequences of integers
sequences = tokenizer.texts_to_sequences(questions)

# Pad sequences to ensure all have the same length
max_sequence_length = max(len(seq) for seq in sequences)
X = pad_sequences(sequences, maxlen=max_sequence_length)

In [8]:
sequences

[[1, 2, 3, 5], [6, 7, 4], [1, 2, 3, 8], [9, 10, 4, 11], [1, 2, 3, 12, 13]]

In [9]:
# Convert answers to numpy array
y = np.array(answers)

# Print the preprocessed data
print("Padded Sequences:\n", X)
print("\nLabels:\n", y)

Padded Sequences:
 [[ 0  1  2  3  5]
 [ 0  0  6  7  4]
 [ 0  1  2  3  8]
 [ 0  9 10  4 11]
 [ 1  2  3 12 13]]

Labels:
 [0 1 0 2 3]


## Build and train a `SimpleRNN` model

The **SimpleRNN** layer processes the input sequences. We use an embedding dimension based on the vocabulary size (number of unique words), followed by a `dense` output layer for classification.

**Training:**
The model is trained for 20 epochs using `sparse_categorical_crossentropy` as the loss function, which is suitable for multi-class classification.


In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Input

In [11]:
# Define the model
model = Sequential()

# Add SimpleRNN layer

# 50 units in the RNN
model.add(SimpleRNN(50, input_shape=(5, 1))) # Sending 1 feature at each time-step

# Output layer (using softmax for multi-class classification)
model.add(Dense(4, activation='softmax'))  # 4 unique answer classes

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X, y, epochs=20, verbose=1)

# Evaluate the model
loss, accuracy = model.evaluate(X, y, verbose=1)
print(f"Model Accuracy: {accuracy:.4f}")


Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.2000 - loss: 1.9859
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 671ms/step - accuracy: 0.2000 - loss: 1.8682
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - accuracy: 0.4000 - loss: 1.7567
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.4000 - loss: 1.6524
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.4000 - loss: 1.5562
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.4000 - loss: 1.4688
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.4000 - loss: 1.3907
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6000 - loss: 1.3220
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 1.2625
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.6000 - loss: 1.2113
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 1.1673
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6000 - loss: 1.1291
Epoch 13/

## Inference

| Questions                       | Answers |
|----------------------------------|---------|
| What is your name?               | 0       |
| How are you?                     | 1       |
| What is your profession?         | 0       |
| Where do you live?               | 2       |
| What is your favorite color?     | 3       |

<br>

You can ask the above questions under `new_question` variable and check the output if they are true.

In [12]:
# New question for inference
new_question = ["How are you?"]

# Tokenize the new question (same tokenizer used during training)
new_sequence = tokenizer.texts_to_sequences(new_question)

# Pad the new sequence to the same length as the training data
new_padded_sequence = pad_sequences(new_sequence, maxlen=max_sequence_length)

# new_padded_sequence = to_categorical(new_padded_sequence, num_classes=vocab_size)

# Make prediction
predicted_probabilities = model.predict(new_padded_sequence)

# Get the predicted class (answer) with the highest probability
predicted_class = np.argmax(predicted_probabilities)

# Print the predicted class
print(f"\nPredicted Answer: {predicted_class}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 533ms/step

Predicted Answer: 1


## Embedding Layer



It's primarily used to map categorical data, such as words or items, into a continuous vector space. This vector space is learned during the training process and allows the model to capture semantic relationships and similarities between the items.

**Commonly used to represent words as dense vectors, capturing semantic similarities and relationships.**

<img src='https://www.researchgate.net/publication/349630764/figure/fig3/AS:999014610788354@1615195052671/Detail-of-the-embedding-layer-of-the-NN-implementing-the-Encoding-model-used-for-the.png' width=400/>

**Benefits:**
* The learned embeddings often capture semantic relationships between the items. For example, words with similar meanings might be located closer together in the embedding space.
* Using embeddings can significantly improve the performance of neural networks on tasks like text classification, machine translation, and recommendation systems.
* Embeddings reduce the high-dimensional categorical data into a lower-dimensional, dense vector space. This makes it easier for the neural network to process and learn patterns.

[`tf.keras.layers.Embedding`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding)


In [13]:
import tensorflow as tf

# Sample input text
input_text = ["hello world", "this is a sentence"]

# Create a vocabulary mapping words to unique indices
vocab = ["hello", "world", "this", "is", "a", "sentence"]
word_to_index = {word: i for i, word in enumerate(vocab)}

In [14]:
# Convert input text to sequences of indices
input_sequences = [[word_to_index[word] for word in sentence.split()] for sentence in input_text]

# Create an embedding layer with a vocabulary size of 6 (matching the number of words),
# an embedding dimension of 10, and padding to ensure all sequences have the same length
embedding_layer = tf.keras.layers.Embedding(input_dim=len(vocab), output_dim=10)


In [15]:
print(input_sequences)

[[0, 1], [2, 3, 4, 5]]


Input sentences represented in a sequence of numbers.

In [16]:
# Pad sequences using tf.keras.preprocessing.sequence.pad_sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences
input_sequences = pad_sequences(input_sequences)

# Convert input_sequences to a tensor
input_sequences = tf.convert_to_tensor(input_sequences)

# Embed the input sequences
embedded_sequences = embedding_layer(input_sequences)

# Print the embedded sequences
print(embedded_sequences)

tf.Tensor(
[[[-0.02405283 -0.03073691  0.02709507 -0.04085281 -0.00851619
   -0.03708656 -0.02054968 -0.04535662 -0.04495146 -0.00806759]
  [-0.02405283 -0.03073691  0.02709507 -0.04085281 -0.00851619
   -0.03708656 -0.02054968 -0.04535662 -0.04495146 -0.00806759]
  [-0.02405283 -0.03073691  0.02709507 -0.04085281 -0.00851619
   -0.03708656 -0.02054968 -0.04535662 -0.04495146 -0.00806759]
  [-0.01379069  0.03475262  0.02833304  0.00818665  0.02325815
   -0.00518384  0.02228986  0.04239818  0.01296797  0.00076644]]

 [[ 0.04238058 -0.04101568  0.00941432 -0.00090975 -0.02838112
    0.00518947 -0.00754134 -0.01735317  0.02870938  0.04599564]
  [ 0.03561736  0.03583357  0.03134284 -0.00431619  0.04234233
    0.01993709  0.04453839 -0.04851894 -0.02968799 -0.01453678]
  [ 0.00481052  0.01910292  0.01233824 -0.03568374  0.03372056
    0.02566941  0.01277887  0.01749952 -0.03254207 -0.00749085]
  [ 0.01914736  0.00511693  0.03383804 -0.03717122 -0.04929255
   -0.01373112  0.01342806 -0.02777

Now both the sentences are represented as a sequence of vectors.

# Sentiment Analysis using RNN

In [17]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load the IMDB dataset
data = tf.keras.datasets.imdb.load_data()
(x_train, y_train), (x_test, y_test) = data

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


All the reviews in this dataset have already been tokenized. <br>
If we check the first review in the training set,

In [18]:
print("First review in the training set:\n", x_train[0], "length:", len(x_train[0]), "class:", y_train[0])


First review in the training set:
 [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32] l

In [19]:
vocab_size = 10000  # Limit the vocabulary size to the top 10,000 words
maxlen = 200  # Limit each review to 200 words

# Pad sequences to have the same length
x_train = pad_sequences(x_train,padding='post',maxlen=maxlen)
x_test = pad_sequences(x_test,padding='post',maxlen=maxlen)


The max length of sequence is quite huge. Hence, we try to limit it to a max length of 100 to avoid inconsistencies while training.

In [20]:
x_train.shape

(25000, 200)

In [21]:

# Create an RNN model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 32),
    tf.keras.layers.SimpleRNN(64),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=10, batch_size=64, validation_split=0.2)

Epoch 1/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 11s 22ms/step - accuracy: 0.5139 - loss: 0.6944 - val_accuracy: 0.5148 - val_loss: 0.6982
Epoch 2/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.5270 - loss: 0.6903 - val_accuracy: 0.5374 - val_loss: 0.6834
Epoch 3/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 10s 17ms/step - accuracy: 0.5708 - loss: 0.6691 - val_accuracy: 0.5668 - val_loss: 0.6623
Epoch 4/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - accuracy: 0.6186 - loss: 0.6444 - val_accuracy: 0.5712 - val_loss: 0.6633
Epoch 5/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - accuracy: 0.6352 - loss: 0.6210 - val_accuracy: 0.5948 - val_loss: 0.6933
Epoch 6/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 11s 17ms/step - accuracy: 0.6532 - loss: 0.6137 - val_accuracy: 0.5438 - val_loss: 0.6749
Epoch 7/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.6106 - loss: 0.6235 - val_accuracy: 0.5332 - val_loss: 0.6698
Epoch 8/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.6282 - loss: 0.5981 - val_

In [23]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {accuracy:.4f}')

782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.5715 - loss: 0.6895
Test Accuracy: 0.5658


In [24]:
# Assuming you have the model and tokenizer defined as in the previous code

tokenizer = Tokenizer(num_words=100)

# Convert a new text to a sequence
new_text = "the movie was bad!"
tokenizer.fit_on_texts(new_text)
new_sequence = tokenizer.texts_to_sequences([new_text])
new_sequence = pad_sequences(new_sequence, maxlen=100)

# Make a prediction
prediction = model.predict(new_sequence)

print(prediction)
# Interpret the prediction (assuming a binary classification task)
if prediction[0][0] > 0.5:
    print("Positive sentiment")
else:
    print("Negative sentiment")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step
[[0.5944504]]
Positive sentiment


## Improvement Strategies

Consider the following strategies to help improve the accuracy of the above model.

1. **Increase max length of sequence:** Increasing the maxlen might help in increasing the accuracy as more information from each review would be available to the model.
2. **Increase the number of epochs**: The model might need more training iterations to learn the patterns in the data effectively.
3. **Add more RNN layers:** Stacking multiple RNN layers can help the model capture more complex dependencies in the sequence.
  * **Increase the number of units in the RNN layers:** More units can enhance the model's capacity to learn intricate patterns.
4. **Adjust the learning rate:** Fine-tuning the learning rate can impact the model's convergence speed and performance.
